Rt 26 move player system
UwUClub/R-Type pull request #16
Opened 2023-09-27 09:11 UTC by BaptisteLaran

## Describe your changes

Add a system that handle player movement

## Issue ticket number and link

https://uwuclub.atlassian.net/browse/RT-26?atlOrigin=eyJpIjoiNjA2ZjU1MjdlOGY2NGQwYzk4MGZhZmM3MjRkMzUwZmYiLCJwIjoiaiJ9

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have documented my code
- [ ] Do we need to implement unit tests?

2023-09-27 09:23 UTC, GlassAlo approved these changes, later dismissed

2023-09-27 09:23 UTC, GlassAlo commented on src/client/System.cpp
> +        std::unordered_map<const Event::KeyIdentifier, std::function<void(float &, Utils::Vector2f &)>> keyMap = {
static const

2023-09-27 09:23 UTC, GlassAlo approved these changes

2023-09-27 09:24 UTC, GlassAlo submitted a review, later dismissed

2023-09-27 09:25 UTC, Beafowl-Pull approved these changes, later dismissed
RAS

2023-09-27 09:26 UTC, Valegox submitted a review, later dismissed

2023-09-27 11:11 UTC, Valegox commented on src/client/SDLDisplayClass.hpp
> +#define SCREEN_WIDTH  1920
constexpr

2023-09-27 11:11 UTC, Valegox commented on src/client/SDLDisplayClass.hpp
> +    private:
remove this

2023-09-27 11:11 UTC, Valegox commented on src/client/SDLDisplayClass.hpp
> +#ifndef SDLDISPLAYClass_HPP_
upper case

2023-09-27 11:11 UTC, Valegox commented on src/client/System.cpp
> +                auto windowEvent = new Event::WindowEvent(1920, 1920, 0, 0, ECS::Event::WindowDisplayState::FULLSCREEN,
1920x1920 ? should it be 1920x1080 ? and use a constexpr pls

2023-09-29 08:12 UTC, GlassAlo requested changes

2023-09-29 08:12 UTC, GlassAlo commented on src/client/System.cpp
> +        static const std::unordered_map<const Event::KeyIdentifier, std::function<void(float &, Utils::Vector2f &)>>
not const key, just const map

2023-09-29 08:12 UTC, GlassAlo commented on src/client/System.cpp
> +    void System::movePlayer(Core::World &world, Core::SparseArray<Utils::Vector2f> &aPos,
Own file

2023-09-29 08:12 UTC, GlassAlo commented on src/client/System.cpp
> +    void System::getInput(Core::World &aWorld)
Own file (System+GetInput.cpp)

2023-09-29 08:12 UTC, GlassAlo commented on src/client/System.cpp
> +    void System::quitSDL(Core::World &aWorld)
Own file (System+QuitSDL.cpp)

2023-09-29 08:12 UTC, GlassAlo commented on src/client/System.cpp
> +    void System::loadTextures(Core::World &aWorld, Core::SparseArray<Utils::LoadedSprite> &aSprites)
Own file (System+LoadTextures.cpp)

2023-09-29 08:12 UTC, GlassAlo commented on src/client/System.cpp
> +    void System::displayEntities(Core::World &aWorld, Core::SparseArray<Utils::LoadedSprite> &aSprites,
Own file (System+DisplayEntities.cpp)

2023-10-02 07:51 UTC, GlassAlo approved these changes

2023-10-02 07:51 UTC, merged