RT-23 init server core + RT-24 client connection
UwUClub/R-Type pull request #4
Opened 2023-09-23 11:13 UTC by Valegox

- Setup `ServerNetworkHandler` and `ClientNetworkHandler`. They both encapsulate `boost::asio` and receive requests asynchronously. The async process requires to create a thread inside each handler, but callbacks stay on the main thread. The `ServerNetworkHandler` stores its client endpoints refered by their entity id.

- Setup a `RTypeProtocol` lib common to RType server and client. It defines `ServerToClientPacket` / `ClientToServerPacket` structs and the `GameEvent` class.

Server launch and client connection can be tested by running each program. For testing, the client sends 3 messages to the server (see `src/client/main.c`).

Serialization and call to ECS systems isn't implemented yet.

2023-09-25 08:54 UTC, Beafowl-Pull submitted a review, later dismissed

2023-09-25 13:55 UTC, Beafowl-Pull approved these changes, later dismissed
RAS

2023-09-26 11:37 UTC, Beafowl-Pull approved these changes, later dismissed
RAS x2

2023-09-27 09:01 UTC, GlassAlo approved these changes, later dismissed

2023-09-27 09:01 UTC, GlassAlo commented on src/client/CMakeLists.txt
> +target_include_directories(client PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/network")
Might be better to put the include in the respective folders using the CMakeLists' folders

2023-09-27 09:01 UTC, GlassAlo commented on src/client/CMakeLists.txt
> +target_include_directories(client PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../rtype_protocol")
same as for line 24

2023-09-27 09:01 UTC, GlassAlo commented on src/ecs/CMakeLists.txt
> +target_include_directories(ecs PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/Event")
Is this useful ? it should be in the CMakeList from the Event Folder

2023-09-27 09:03 UTC, Beafowl-Pull requested changes
Just a thing but it's globally good

2023-09-27 09:03 UTC, Beafowl-Pull commented on CMakeLists.txt
> +if (GCC)
remove this, it's useless

2023-09-27 10:39 UTC, Beafowl-Pull approved these changes
RAS

2023-09-27 10:39 UTC, merged